improve resilience

diff --git a/jjb/oom-template.yaml b/jjb/oom-template.yaml
--- a/jjb/oom-template.yaml
+++ b/jjb/oom-template.yaml
@@ -295,24 +295,24 @@
           $WORKSPACE/test/ete/scripts/teardown-onap.sh -q
           cd $WORKSPACE/deployment/heat/onap-oom
           envsubst < $ENV_FILE > $ENV_FILE~
-          if ! openstack stack create -t ./onap-oom.yaml -e $ENV_FILE~ onap-oom --parameter docker_manifest={docker_manifest} --parameter integration_gerrit_branch={gerrit_branch} --parameter integration_gerrit_refspec={gerrit_refspec}; then
+          if ! openstack stack create -t ./onap-oom.yaml -e $ENV_FILE~ {env-name} --parameter docker_manifest={docker_manifest} --parameter integration_gerrit_branch={gerrit_branch} --parameter integration_gerrit_refspec={gerrit_refspec}; then
             exit 1
           fi
-          while [ "CREATE_IN_PROGRESS" == "$(openstack stack show -c stack_status -f value onap-oom)" ]; do
+          while [ "CREATE_IN_PROGRESS" == "$(openstack stack show -c stack_status -f value {env-name}" ]; do
             sleep 30
           done
 
-          STATUS=$(openstack stack show -c stack_status -f value onap-oom)
+          STATUS=$(openstack stack show -c stack_status -f value {env-name})
           echo $STATUS
           if [ "CREATE_COMPLETE" != "$STATUS" ]; then
-            openstack stack show -c stack_status_reason -f value onap-oom
+            openstack stack show -c stack_status_reason -f value {env-name}
             exit 1
           fi
 
           for i in $(seq 1 30); do
             sleep 30
-            RANCHER_IP=$(openstack stack output show onap-oom rancher_vm_ip -c output_value -f value)
-            K8S_IP=$(openstack stack output show onap-oom k8s_1_vm_ip -c output_value -f value)
+            RANCHER_IP=$(openstack stack output show {env-name} rancher_vm_ip -c output_value -f value)
+            K8S_IP=$(openstack stack output show {env-name} k8s_1_vm_ip -c output_value -f value)
             timeout 1 ping -c 1 "$RANCHER_IP" && break
           done
           sleep 2m
@@ -335,6 +335,8 @@
             sleep 10m
             ROBOT_POD=$(ssh -i $SSH_KEY ubuntu@$RANCHER_IP 'sudo su -c "kubectl --namespace onap get pods"' | grep robot | sed 's/ .*//')
             if [ "$ROBOT_POD" == "" ]; then
+              # kubectl failed; restart dockerd in rancher VM
+              ssh -i $SSH_KEY ubuntu@$RANCHER_IP 'sudo su -c "systemctl restart docker"'
               continue
             fi
             ssh -i $SSH_KEY ubuntu@$RANCHER_IP  'sudo su -l root -c "/root/oom/kubernetes/robot/ete-k8s.sh onap health"'
@@ -418,6 +420,7 @@
           fail: true
     builders:
       - run-oom-ete:
+          env-name: '{env}'
           lab-name: '{lab-name}'
           tenant-name: '{tenant-name}'
           docker_manifest: 'docker-manifest.csv'
@@ -447,6 +450,7 @@
     triggers: '{obj:triggers_var}'
     builders:
       - run-oom-ete:
+          env-name: '{env}'
           lab-name: '{lab-name}'
           tenant-name: '{tenant-name}'
           docker_manifest: 'docker-manifest.csv'
@@ -479,6 +483,7 @@
     triggers: '{obj:triggers_var}'
     builders:
       - run-oom-ete:
+          env-name: '{env}'
           lab-name: '{lab-name}'
           tenant-name: '{tenant-name}'
           docker_manifest: 'docker-manifest-staging.csv'
